compile:
	pandoc cv2024_fr.md -s -c https://lerina.github.io/css/vpkely.css --toc -o newcv2024_fr.html
	pandoc cv2024_fr.md -V papersize:a4  -o newcv2024_fr.pdf	
	pandoc cv2024.md -s -c https://lerina.github.io/css/vpkely.css --toc -o en_cv2024.html
	pandoc cv2024.md --template=template.tex --pdf-engine=xelatex -o en_cv2024.pdf
    
